---
# tasks file for ansible-lxc

# specify the packages to install
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ansible_os_family}}.yml"

- name: install lxc and lxd ppa (ubuntu)
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - 'ppa:ubuntu-lxc/lxc-stable'
    - 'ppa:ubuntu-lxc/lxd-stable'
  when: ansible_distribution == 'Ubuntu'

- name: install packages
  package: name={{lxc_pkgs}} state={{lxc_pkg_state}}

# # quirks on non-Ubuntu Os.
# - include: quirks.yml
#   when: ansible_distribution != 'Ubuntu'

# fixme: This doesn't work. it
# unpriv users setup
# don't bother doing this unless you know your distribution supports
# unprivileged containers.
# - include: ubuntu_unpriv_templating.yml
#   when: ansible_distribution == 'Ubuntu'

  # LXC configuration is split in two parts:
  #   - container ( /etc/lxc/default.conf && ~/.config/lxc/default.conf )
  #   - system  ( /etc/lxc/lxc.conf && ~/.config/lxc/lxc.conf )
  #
  # And also:
  #   - /etc/lxc/lxc-usernet (unprivileged user network administration file)

- name: template system-wide default.conf and lxc.conf
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    backup: yes
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: default.conf.j2, dest: /etc/lxc/default.conf }
    - { src: lxc.conf.j2, dest: /etc/lxc/lxc.conf }

# needed to attach to ovs bridge device. openvswitch is not available on CentOS
# repos. LXD is able to manage openvswitch bridge and this should not be
# required.
- name: install ovs ifupdown scripts
  copy:
    src: "{{item}}"
    dest: /etc/lxc/
    mode: 0774
    owner: root
    group: root
  with_items:
    - 'ifdown'
    - 'ifup'
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int <= "7") or
        (ansible_distribution != "Centos")

# This file is normaly auto-generated by lxc.postinst
# - name: configure lxc-net on Ubuntu derivatives
#   template:
#     src: lxc-net.j2
#     dest: /etc/default/lxc-net
#     owner: root
#     group: root
#     mode: 0644
#     backup: yes
#   when: ansible_distribution == 'Ubuntu'

# - name: add entry in dnsmasq.conf to allow DNS resolution
#   lineinfile:
#     dest: /etc/dnsmasq.conf
#     regexp: ^#?server=/\w/\d{3}.*
#     instertafter: ^#server=/localnet/192.168.0.1
#     line: server=lxc/{{lxc_net_addr}}/
#     backup: yes
#   handlers: restart dnsmasq
