---
# tasks file for ansible-lxc

# specify the packages to install
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install ubuntu ppa
  apt_repository:
    repo: 'ppa:ubuntu-lxc/lxc-stable'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: install packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state={{ lxc_pkg_state }}"
  with_items: lxc_packages

- name: create missing directories in each lxc administrator account
  file:
    path: /home/{{ item[0].name }}/{{ item[1] }}
    owner: "{{ item[0].name }}"
    group: "{{ item[0].name }}"
    mode: 0755
    state: directory
  with_nested:
    - "{{ users }}"
    - "{{ lxc_directories }}"
  when: lxc_admin == yes

- name: create missing files
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0644
    state: touch
  with_items:
    - /etc/subuid
    - /etc/subgid
  when: ansible_distribution != 'Ubuntu'

  # LXC configuration is split in two parts:
  #   - container ( /etc/lxc/default.conf | ~/.config/lxc/default.conf )
  #   - system  ( /etc/lxc/lxc.conf | ~/.config/lxc/lxc.conf )
  #
  # And:
  #   - /etc/lxc/lxc-usernet (unprivileged user network administration file)

# file is placed inside user home to allow creation of unprivileged containers
- name: template ~/.config/lxc/default.conf (user default container conf)
  template:
    src: user_default.conf.j2
    dest: "/home/{{ item.name }}/.config/lxc/default.conf"
    backup: yes
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: users
  when: lxc_admin == yes

# file is placed inside user home to allow creation of unprivileged containers
- name: template ~/.config/lxc/lxc.conf (path and storage BE)
  template:
    src: lxc.conf.j2
    dest: "/home/{{ item.name }}/.config/lxc/lxc.conf"
    backup: yes
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: users
  when: item.lxc_admin == yes

- name: template /etc/lxc/default.conf (system-wide default container conf)
  template:
    src: default.conf.j2
    dest: /etc/lxc/default.conf
    backup: yes
    mode: 0644
    owner: root
    group: root

- name: template /etc/lxc/lxc.conf (path and storage BE)
  template:
    src: lxc.conf.j2
    dest: /etc/lxc/lxc.conf
    backup: yes
    mode: 0644
    owner: root
    group: root

- name: template /etc/lxc/lxc-usernet (unprivileged user network administration file)
  template:
    src: lxc-usernet.j2
    dest: /etc/lxc/lxc-usernet
    backup: yes
    mode: 0644
    owner: root
    group: root

# - name: add entry in dnsmasq.conf to allow DNS resolution
#   lineinfile:
#     dest: /etc/dnsmasq.conf
#     regexp: ^#?server=/\w/\d{3}.*
#     instertafter: ^#server=/localnet/192.168.0.1
#     line: server=lxc/{{ lxc_net_addr }}/
#     backup: yes
#   handlers: restart dnsmasq

# # this is to run unprivileged containers
# # fixme: allocate additional uids & and gids to a username
# sudo usermod --add-subuids 100000-165536 username
# sudo usermod --add-subgids 100000-165536 username

# see config/init/common/lxc-net.in script inside lxc github repos for details
# of lxcbr0 bridge instantiation.

# - name: Ensure networking includes interfaces.d
#   lineinfile:
#     dest: "/etc/network/interfaces"
#     line: "source /etc/network/interfaces.d/*.conf"
#     backup: "yes"
#   when: ansible_distribution == 'Ubuntu'

# - name: Template lxc bridge configuration
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ item.owner|default('root') }}"
#     group: "{{ item.group|default('root') }}"
#     mode: "{{ item.mode|default('0644') }}"
#   with_items:
#   - { src: lxc-bridge.cfg.j2, dest: "/etc/network/interfaces.d/lxc-bridge.cfg" }
#   when: ansible_distribution == 'Ubuntu'
