---

# quirks on non-Ubuntu Os.

- name: touch missing files
  file:
    path: "{{item}}"
    owner: root
    group: root
    mode: 0644
    state: touch
  with_items:
    - /etc/subuid
    - /etc/subgid
